cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'git'
brew 'curl'
brew 'tmux'
brew 'coreutils'
brew 'imagemagick'
brew 'libgit2'
brew 'openssl'
brew 'readline'
brew 'xz'
brew 'wget'
brew 'youtube-dl'
brew 'ruby'
brew 'rbenv'
brew 'the_silver_searcher'
brew 'tcl-tk'
brew 'bitwarden-cli'
brew 'ffmpeg'

cask 'alfred'
cask 'rectangle'
cask 'zotero'
cask 'dropbox'
cask 'dynalist'
cask 'pdf-expert'
cask 'zoom'
